[2024-10-24T01:22:52.857+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-25T08:00:00+00:00 [queued]>
[2024-10-24T01:22:52.920+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-25T08:00:00+00:00 [queued]>
[2024-10-24T01:22:52.920+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2024-10-24T01:22:52.965+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): Silver> on 2023-11-25 08:00:00+00:00
[2024-10-24T01:22:53.032+0000] {standard_task_runner.py:57} INFO - Started process 8044 to run task
[2024-10-24T01:22:53.079+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_openbrewerydb_to_silver_gold', 'Silver', 'scheduled__2023-11-25T08:00:00+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/api_openbrewerydb_to_silver.py', '--cfg-path', '/tmp/tmpy5pz22l2']
[2024-10-24T01:22:53.179+0000] {standard_task_runner.py:85} INFO - Job 123: Subtask Silver
[2024-10-24T01:22:53.962+0000] {task_command.py:415} INFO - Running <TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-25T08:00:00+00:00 [running]> on host de5108c6da1d
[2024-10-24T01:22:55.000+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rodrigo Araujo' AIRFLOW_CTX_DAG_ID='api_openbrewerydb_to_silver_gold' AIRFLOW_CTX_TASK_ID='Silver' AIRFLOW_CTX_EXECUTION_DATE='2023-11-25T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-25T08:00:00+00:00'
[2024-10-24T01:22:55.220+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2024-10-24T01:22:55.222+0000] {spark_submit.py:363} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark --queue root.default jobs/silver/api_openbrewerydb.py
[2024-10-24T01:23:24.047+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-10-24T01:24:56.291+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-10-24T01:26:26.034+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-10-24T01:26:26.078+0000] {process_utils.py:131} INFO - Sending 15 to group 8044. PIDs of all processes in the group: [8046, 8044]
[2024-10-24T01:26:26.078+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 8044
[2024-10-24T01:26:26.079+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-10-24T01:26:26.080+0000] {spark_submit.py:654} INFO - Sending kill signal to spark-submit
[2024-10-24T01:26:27.293+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 183, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 438, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 492, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-10-24T01:26:27.320+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=api_openbrewerydb_to_silver_gold, task_id=Silver, execution_date=20231125T080000, start_date=20241024T012252, end_date=20241024T012627
[2024-10-24T01:26:27.485+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 123 for task Silver (Task received SIGTERM signal; 8044)
[2024-10-24T01:26:27.598+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=8044, status='terminated', exitcode=1, started='01:22:52') (8044) terminated with exit code 1
[2024-10-24T01:26:27.599+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=8046, status='terminated', started='01:22:54') (8046) terminated with exit code None
[2024-10-24T14:33:59.195+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-25T08:00:00+00:00/task_id=Silver permission to 509
[2024-10-24T14:33:59.203+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-25T08:00:00+00:00/task_id=Silver permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-25T08:00:00+00:00/task_id=Silver'
[2024-10-24T14:33:59.257+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-25T08:00:00+00:00/task_id=Silver permission to 509
[2024-10-24T14:33:59.257+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-25T08:00:00+00:00/task_id=Silver permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-25T08:00:00+00:00/task_id=Silver'
[2024-10-24T14:33:59.315+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-25T08:00:00+00:00 [queued]>
[2024-10-24T14:33:59.327+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-25T08:00:00+00:00 [queued]>
[2024-10-24T14:33:59.328+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-10-24T14:33:59.347+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): Silver> on 2023-11-25 08:00:00+00:00
[2024-10-24T14:33:59.354+0000] {standard_task_runner.py:57} INFO - Started process 11387 to run task
[2024-10-24T14:33:59.358+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_openbrewerydb_to_silver_gold', 'Silver', 'scheduled__2023-11-25T08:00:00+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/api_openbrewerydb_to_silver.py', '--cfg-path', '/tmp/tmp9dyzytbu']
[2024-10-24T14:33:59.361+0000] {standard_task_runner.py:85} INFO - Job 75: Subtask Silver
[2024-10-24T14:33:59.453+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-25T08:00:00+00:00/task_id=Silver permission to 509
[2024-10-24T14:33:59.453+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-25T08:00:00+00:00/task_id=Silver permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-25T08:00:00+00:00/task_id=Silver'
[2024-10-24T14:33:59.454+0000] {task_command.py:415} INFO - Running <TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-25T08:00:00+00:00 [running]> on host 96f89615839b
[2024-10-24T14:33:59.608+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rodrigo Araujo' AIRFLOW_CTX_DAG_ID='api_openbrewerydb_to_silver_gold' AIRFLOW_CTX_TASK_ID='Silver' AIRFLOW_CTX_EXECUTION_DATE='2023-11-25T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-25T08:00:00+00:00'
[2024-10-24T14:33:59.629+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2024-10-24T14:33:59.630+0000] {spark_submit.py:363} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark jobs/silver/api_openbrewerydb.py
[2024-10-24T14:34:03.209+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO SparkContext: Running Spark version 3.5.3
[2024-10-24T14:34:03.212+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO SparkContext: OS info Linux, 5.15.0-124-generic, amd64
[2024-10-24T14:34:03.213+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO SparkContext: Java version 11.0.25
[2024-10-24T14:34:03.269+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-10-24T14:34:03.352+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO ResourceUtils: ==============================================================
[2024-10-24T14:34:03.352+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-10-24T14:34:03.352+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO ResourceUtils: ==============================================================
[2024-10-24T14:34:03.353+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO SparkContext: Submitted application: IngestaoSilver
[2024-10-24T14:34:03.374+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-10-24T14:34:03.388+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO ResourceProfile: Limiting resource is cpu
[2024-10-24T14:34:03.389+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-10-24T14:34:03.434+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO SecurityManager: Changing view acls to: ***
[2024-10-24T14:34:03.435+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO SecurityManager: Changing modify acls to: ***
[2024-10-24T14:34:03.435+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO SecurityManager: Changing view acls groups to:
[2024-10-24T14:34:03.436+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO SecurityManager: Changing modify acls groups to:
[2024-10-24T14:34:03.436+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-10-24T14:34:03.650+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO Utils: Successfully started service 'sparkDriver' on port 37271.
[2024-10-24T14:34:03.671+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO SparkEnv: Registering MapOutputTracker
[2024-10-24T14:34:03.700+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO SparkEnv: Registering BlockManagerMaster
[2024-10-24T14:34:03.718+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-10-24T14:34:03.719+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-10-24T14:34:03.722+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-10-24T14:34:03.740+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-c4fccdee-1b73-42cf-87ef-cb91b0abd4e4
[2024-10-24T14:34:03.753+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-10-24T14:34:03.766+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-10-24T14:34:03.893+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-10-24T14:34:03.939+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:03 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-10-24T14:34:04.039+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2024-10-24T14:34:04.080+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.2:7077 after 24 ms (0 ms spent in bootstraps)
[2024-10-24T14:34:04.155+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20241024143404-0070
[2024-10-24T14:34:04.160+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241024143404-0070/0 on worker-20241024142308-172.18.0.5-43899 (172.18.0.5:43899) with 2 core(s)
[2024-10-24T14:34:04.162+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO StandaloneSchedulerBackend: Granted executor ID app-20241024143404-0070/0 on hostPort 172.18.0.5:43899 with 2 core(s), 1024.0 MiB RAM
[2024-10-24T14:34:04.192+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 35889.
[2024-10-24T14:34:04.192+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO NettyBlockTransferService: Server created on 96f89615839b:35889
[2024-10-24T14:34:04.192+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-10-24T14:34:04.199+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 96f89615839b, 35889, None)
[2024-10-24T14:34:04.206+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO BlockManagerMasterEndpoint: Registering block manager 96f89615839b:35889 with 434.4 MiB RAM, BlockManagerId(driver, 96f89615839b, 35889, None)
[2024-10-24T14:34:04.226+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 96f89615839b, 35889, None)
[2024-10-24T14:34:04.227+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 96f89615839b, 35889, None)
[2024-10-24T14:34:04.235+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241024143404-0070/0 is now RUNNING
[2024-10-24T14:34:04.495+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-10-24T14:34:04.672+0000] {spark_submit.py:524} INFO - Hello from Spark!
[2024-10-24T14:34:04.673+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-10-24T14:34:04.683+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO SparkUI: Stopped Spark web UI at http://96f89615839b:4040
[2024-10-24T14:34:04.688+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-10-24T14:34:04.691+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-10-24T14:34:04.707+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-10-24T14:34:04.716+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO MemoryStore: MemoryStore cleared
[2024-10-24T14:34:04.717+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO BlockManager: BlockManager stopped
[2024-10-24T14:34:04.722+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-10-24T14:34:04.726+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-10-24T14:34:04.732+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:04 INFO SparkContext: Successfully stopped SparkContext
[2024-10-24T14:34:05.115+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:05 INFO ShutdownHookManager: Shutdown hook called
[2024-10-24T14:34:05.116+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:05 INFO ShutdownHookManager: Deleting directory /tmp/spark-0f96eedb-e520-475c-b9d3-8ec3fd6085b3
[2024-10-24T14:34:05.119+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:05 INFO ShutdownHookManager: Deleting directory /tmp/spark-f26ce7b3-43ce-428b-920c-e8e50a5913fe
[2024-10-24T14:34:05.122+0000] {spark_submit.py:524} INFO - 24/10/24 14:34:05 INFO ShutdownHookManager: Deleting directory /tmp/spark-f26ce7b3-43ce-428b-920c-e8e50a5913fe/pyspark-603335f6-e1ca-4390-beb9-bf424c311890
[2024-10-24T14:34:05.184+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=api_openbrewerydb_to_silver_gold, task_id=Silver, execution_date=20231125T080000, start_date=20241024T143359, end_date=20241024T143405
[2024-10-24T14:34:05.209+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-10-24T14:34:05.232+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
