[2024-10-24T01:27:00.039+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-12-06T08:00:00+00:00 [queued]>
[2024-10-24T01:27:00.058+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-12-06T08:00:00+00:00 [queued]>
[2024-10-24T01:27:00.059+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2024-10-24T01:27:00.088+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): Silver> on 2023-12-06 08:00:00+00:00
[2024-10-24T01:27:00.125+0000] {standard_task_runner.py:57} INFO - Started process 9024 to run task
[2024-10-24T01:27:00.152+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_openbrewerydb_to_silver_gold', 'Silver', 'scheduled__2023-12-06T08:00:00+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/api_openbrewerydb_to_silver.py', '--cfg-path', '/tmp/tmpg1zx83e3']
[2024-10-24T01:27:00.168+0000] {standard_task_runner.py:85} INFO - Job 145: Subtask Silver
[2024-10-24T01:27:00.519+0000] {task_command.py:415} INFO - Running <TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-12-06T08:00:00+00:00 [running]> on host de5108c6da1d
[2024-10-24T01:27:01.160+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rodrigo Araujo' AIRFLOW_CTX_DAG_ID='api_openbrewerydb_to_silver_gold' AIRFLOW_CTX_TASK_ID='Silver' AIRFLOW_CTX_EXECUTION_DATE='2023-12-06T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-06T08:00:00+00:00'
[2024-10-24T01:27:01.212+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2024-10-24T01:27:01.214+0000] {spark_submit.py:363} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark --queue root.default jobs/silver/api_openbrewerydb.py
[2024-10-24T01:27:31.949+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:31 INFO SparkContext: Running Spark version 3.5.3
[2024-10-24T01:27:31.978+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:31 INFO SparkContext: OS info Linux, 5.15.0-124-generic, amd64
[2024-10-24T01:27:31.979+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:31 INFO SparkContext: Java version 11.0.25
[2024-10-24T01:27:32.530+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:32 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-10-24T01:27:33.214+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:33 INFO ResourceUtils: ==============================================================
[2024-10-24T01:27:33.217+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:33 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-10-24T01:27:33.230+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:33 INFO ResourceUtils: ==============================================================
[2024-10-24T01:27:33.232+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:33 INFO SparkContext: Submitted application: IngestaoSilver
[2024-10-24T01:27:33.485+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:33 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-10-24T01:27:33.747+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:33 INFO ResourceProfile: Limiting resource is cpu
[2024-10-24T01:27:33.750+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:33 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-10-24T01:27:34.364+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO SecurityManager: Changing view acls to: ***
[2024-10-24T01:27:34.366+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO SecurityManager: Changing modify acls to: ***
[2024-10-24T01:27:34.378+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO SecurityManager: Changing view acls groups to:
[2024-10-24T01:27:34.380+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO SecurityManager: Changing modify acls groups to:
[2024-10-24T01:27:34.390+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-10-24T01:27:37.002+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:37 INFO Utils: Successfully started service 'sparkDriver' on port 34223.
[2024-10-24T01:27:37.336+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:37 INFO SparkEnv: Registering MapOutputTracker
[2024-10-24T01:27:37.693+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:37 INFO SparkEnv: Registering BlockManagerMaster
[2024-10-24T01:27:38.149+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:38 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-10-24T01:27:38.157+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:38 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-10-24T01:27:38.212+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:38 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-10-24T01:27:38.451+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:38 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-adb43e7a-e208-4fa1-a55b-c8fa75e7a0ac
[2024-10-24T01:27:38.585+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:38 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-10-24T01:27:38.788+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:38 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-10-24T01:27:41.594+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:41 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-10-24T01:27:42.465+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:42 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2024-10-24T01:27:42.476+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:42 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2024-10-24T01:27:42.484+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:42 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2024-10-24T01:27:42.505+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:42 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2024-10-24T01:27:42.509+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:42 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2024-10-24T01:27:42.516+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:42 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
[2024-10-24T01:27:42.533+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:42 WARN Utils: Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
[2024-10-24T01:27:42.535+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:42 WARN Utils: Service 'SparkUI' could not bind on port 4047. Attempting port 4048.
[2024-10-24T01:27:42.536+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:42 WARN Utils: Service 'SparkUI' could not bind on port 4048. Attempting port 4049.
[2024-10-24T01:27:42.541+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:42 WARN Utils: Service 'SparkUI' could not bind on port 4049. Attempting port 4050.
[2024-10-24T01:27:42.668+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:42 INFO Utils: Successfully started service 'SparkUI' on port 4050.
[2024-10-24T01:29:30.872+0000] {spark_submit.py:524} INFO - 24/10/24 01:29:30 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2024-10-24T01:29:55.420+0000] {spark_submit.py:524} INFO - 24/10/24 01:29:54 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2024-10-24T01:30:52.670+0000] {spark_submit.py:524} INFO - 24/10/24 01:30:52 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2024-10-24T01:31:12.168+0000] {spark_submit.py:524} INFO - 24/10/24 01:31:11 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2024-10-24T01:31:14.977+0000] {spark_submit.py:524} INFO - 24/10/24 01:31:14 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2024-10-24T01:32:29.670+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 215, in heartbeat
    heartbeat_callback(session)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/local_task_job_runner.py", line 246, in heartbeat_callback
    self.task_instance.refresh_from_db()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 864, in refresh_from_db
    ti = qry.one_or_none()
         ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-10-24T01:33:47.883+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-10-24T01:33:59.654+0000] {spark_submit.py:524} INFO - 24/10/24 01:33:59 ERROR RpcOutboxMessage: Ask terminated before connecting successfully
[2024-10-24T01:33:59.657+0000] {spark_submit.py:524} INFO - 24/10/24 01:33:59 ERROR RpcOutboxMessage: Ask terminated before connecting successfully
[2024-10-24T01:33:59.658+0000] {spark_submit.py:524} INFO - 24/10/24 01:33:59 ERROR RpcOutboxMessage: Ask terminated before connecting successfully
[2024-10-24T01:33:59.659+0000] {spark_submit.py:524} INFO - 24/10/24 01:33:02 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark-master:7077
[2024-10-24T01:33:59.659+0000] {spark_submit.py:524} INFO - org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [120 seconds]. This timeout is controlled by spark.rpc.lookupTimeout
[2024-10-24T01:33:59.660+0000] {spark_submit.py:524} INFO - at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:47)
[2024-10-24T01:33:59.660+0000] {spark_submit.py:524} INFO - at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:62)
[2024-10-24T01:33:59.660+0000] {spark_submit.py:524} INFO - at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:58)
[2024-10-24T01:33:59.660+0000] {spark_submit.py:524} INFO - at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
[2024-10-24T01:33:59.661+0000] {spark_submit.py:524} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:76)
[2024-10-24T01:33:59.661+0000] {spark_submit.py:524} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-10-24T01:33:59.661+0000] {spark_submit.py:524} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-10-24T01:33:59.661+0000] {spark_submit.py:524} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-10-24T01:33:59.662+0000] {spark_submit.py:524} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2024-10-24T01:33:59.662+0000] {spark_submit.py:524} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-10-24T01:33:59.662+0000] {spark_submit.py:524} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2024-10-24T01:33:59.662+0000] {spark_submit.py:524} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2024-10-24T01:33:59.663+0000] {spark_submit.py:524} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-10-24T01:33:59.702+0000] {spark_submit.py:524} INFO - Caused by: java.util.concurrent.TimeoutException: Futures timed out after [120 seconds]
[2024-10-24T01:33:59.703+0000] {spark_submit.py:524} INFO - at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
[2024-10-24T01:33:59.703+0000] {spark_submit.py:524} INFO - at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
[2024-10-24T01:33:59.704+0000] {spark_submit.py:524} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:48)
[2024-10-24T01:33:59.704+0000] {spark_submit.py:524} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-10-24T01:33:59.704+0000] {spark_submit.py:524} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-10-24T01:33:59.704+0000] {spark_submit.py:524} INFO - ... 8 more
[2024-10-24T01:33:59.806+0000] {spark_submit.py:524} INFO - 24/10/24 01:33:59 INFO TransportClientFactory: Successfully created connection to spark-master/172.22.0.3:7077 after 141580 ms (1957 ms spent in bootstraps)
[2024-10-24T01:33:59.831+0000] {spark_submit.py:524} INFO - 24/10/24 01:33:59 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 45521.
[2024-10-24T01:33:59.846+0000] {spark_submit.py:524} INFO - 24/10/24 01:33:59 INFO NettyBlockTransferService: Server created on de5108c6da1d:45521
[2024-10-24T01:33:59.871+0000] {spark_submit.py:524} INFO - 24/10/24 01:33:59 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-10-24T01:34:00.595+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:00 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, de5108c6da1d, 45521, None)
[2024-10-24T01:34:00.645+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:00 INFO BlockManagerMasterEndpoint: Registering block manager de5108c6da1d:45521 with 434.4 MiB RAM, BlockManagerId(driver, de5108c6da1d, 45521, None)
[2024-10-24T01:34:00.662+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:00 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, de5108c6da1d, 45521, None)
[2024-10-24T01:34:00.673+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:00 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, de5108c6da1d, 45521, None)
[2024-10-24T01:34:01.466+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:01 WARN NettyRpcEnv: Ignored message: true
[2024-10-24T01:34:01.468+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:01 WARN NettyRpcEnv: Ignored message: true
[2024-10-24T01:34:01.474+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:01 WARN NettyRpcEnv: Ignored message: true
[2024-10-24T01:35:24.590+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-10-24T01:35:24.659+0000] {process_utils.py:131} INFO - Sending 15 to group 9024. PIDs of all processes in the group: [9115, 9638, 9024]
[2024-10-24T01:35:24.669+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 9024
[2024-10-24T01:35:24.678+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-10-24T01:35:24.704+0000] {spark_submit.py:654} INFO - Sending kill signal to spark-submit
[2024-10-24T01:35:24.945+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 183, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 438, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 492, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-10-24T01:35:25.022+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=api_openbrewerydb_to_silver_gold, task_id=Silver, execution_date=20231206T080000, start_date=20241024T012700, end_date=20241024T013524
[2024-10-24T01:35:25.221+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 145 for task Silver (Task received SIGTERM signal; 9024)
[2024-10-24T01:35:25.261+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=9115, status='terminated', started='01:27:00') (9115) terminated with exit code None
[2024-10-24T01:35:25.262+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=9024, status='terminated', exitcode=1, started='01:26:59') (9024) terminated with exit code 1
[2024-10-24T01:35:25.262+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=9638, status='terminated', started='01:27:23') (9638) terminated with exit code None
