[2024-10-24T01:26:57.464+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-29T08:00:00+00:00 [queued]>
[2024-10-24T01:26:57.483+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-29T08:00:00+00:00 [queued]>
[2024-10-24T01:26:57.484+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2024-10-24T01:26:57.518+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): Silver> on 2023-11-29 08:00:00+00:00
[2024-10-24T01:26:57.528+0000] {standard_task_runner.py:57} INFO - Started process 8821 to run task
[2024-10-24T01:26:57.552+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_openbrewerydb_to_silver_gold', 'Silver', 'scheduled__2023-11-29T08:00:00+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/api_openbrewerydb_to_silver.py', '--cfg-path', '/tmp/tmpaoncu_ov']
[2024-10-24T01:26:57.579+0000] {standard_task_runner.py:85} INFO - Job 138: Subtask Silver
[2024-10-24T01:26:57.768+0000] {task_command.py:415} INFO - Running <TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-29T08:00:00+00:00 [running]> on host de5108c6da1d
[2024-10-24T01:26:58.088+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rodrigo Araujo' AIRFLOW_CTX_DAG_ID='api_openbrewerydb_to_silver_gold' AIRFLOW_CTX_TASK_ID='Silver' AIRFLOW_CTX_EXECUTION_DATE='2023-11-29T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-29T08:00:00+00:00'
[2024-10-24T01:26:58.140+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2024-10-24T01:26:58.141+0000] {spark_submit.py:363} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark --queue root.default jobs/silver/api_openbrewerydb.py
[2024-10-24T01:27:29.634+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:29 INFO SparkContext: Running Spark version 3.5.3
[2024-10-24T01:27:29.654+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:29 INFO SparkContext: OS info Linux, 5.15.0-124-generic, amd64
[2024-10-24T01:27:29.656+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:29 INFO SparkContext: Java version 11.0.25
[2024-10-24T01:27:30.309+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-10-24T01:27:30.753+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO ResourceUtils: ==============================================================
[2024-10-24T01:27:30.754+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-10-24T01:27:30.756+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO ResourceUtils: ==============================================================
[2024-10-24T01:27:30.758+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO SparkContext: Submitted application: IngestaoSilver
[2024-10-24T01:27:30.846+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-10-24T01:27:30.886+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO ResourceProfile: Limiting resource is cpu
[2024-10-24T01:27:30.889+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:30 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-10-24T01:27:31.163+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:31 INFO SecurityManager: Changing view acls to: ***
[2024-10-24T01:27:31.165+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:31 INFO SecurityManager: Changing modify acls to: ***
[2024-10-24T01:27:31.167+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:31 INFO SecurityManager: Changing view acls groups to:
[2024-10-24T01:27:31.170+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:31 INFO SecurityManager: Changing modify acls groups to:
[2024-10-24T01:27:31.172+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:31 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-10-24T01:27:32.963+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:32 INFO Utils: Successfully started service 'sparkDriver' on port 44123.
[2024-10-24T01:27:33.345+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:33 INFO SparkEnv: Registering MapOutputTracker
[2024-10-24T01:27:33.688+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:33 INFO SparkEnv: Registering BlockManagerMaster
[2024-10-24T01:27:34.078+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-10-24T01:27:34.081+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-10-24T01:27:34.104+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-10-24T01:27:34.409+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-f46f8263-bb00-4bcc-8314-c73b4b39d6fd
[2024-10-24T01:27:34.580+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-10-24T01:27:34.831+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-10-24T01:27:36.301+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:36 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-10-24T01:27:37.042+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:37 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-10-24T01:27:38.525+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:38 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2024-10-24T01:27:39.146+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:39 INFO TransportClientFactory: Successfully created connection to spark-master/172.22.0.3:7077 after 492 ms (0 ms spent in bootstraps)
[2024-10-24T01:27:39.866+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:39 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20241024012739-0042
[2024-10-24T01:27:39.896+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:39 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241024012739-0042/0 on worker-20241024010948-172.22.0.4-41535 (172.22.0.4:41535) with 2 core(s)
[2024-10-24T01:27:39.977+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:39 INFO StandaloneSchedulerBackend: Granted executor ID app-20241024012739-0042/0 on hostPort 172.22.0.4:41535 with 2 core(s), 1024.0 MiB RAM
[2024-10-24T01:27:40.035+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:40 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 44815.
[2024-10-24T01:27:40.037+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:40 INFO NettyBlockTransferService: Server created on de5108c6da1d:44815
[2024-10-24T01:27:40.146+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:40 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241024012739-0042/0 is now RUNNING
[2024-10-24T01:27:40.176+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:40 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-10-24T01:27:40.488+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:40 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, de5108c6da1d, 44815, None)
[2024-10-24T01:27:40.497+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:40 INFO BlockManagerMasterEndpoint: Registering block manager de5108c6da1d:44815 with 434.4 MiB RAM, BlockManagerId(driver, de5108c6da1d, 44815, None)
[2024-10-24T01:27:40.524+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:40 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, de5108c6da1d, 44815, None)
[2024-10-24T01:27:40.565+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:40 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, de5108c6da1d, 44815, None)
[2024-10-24T01:27:53.206+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:52 INFO AsyncEventQueue: Process of event SparkListenerApplicationStart(IngestaoSilver,Some(app-20241024012739-0042),1729733249534,***,None,None,None) by listener AppStatusListener took 1.240299874s.
[2024-10-24T01:28:59.574+0000] {spark_submit.py:524} INFO - 24/10/24 01:28:59 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-10-24T01:29:00.112+0000] {spark_submit.py:524} INFO - 24/10/24 01:29:00 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@339be4a8)) by listener AppStatusListener took 1.078915674s.
[2024-10-24T01:31:11.478+0000] {spark_submit.py:524} INFO - 24/10/24 01:31:10 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@64136f37)) by listener AppStatusListener took 2.512613804s.
[2024-10-24T01:32:46.424+0000] {spark_submit.py:524} INFO - 24/10/24 01:32:44 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@84169b9)) by listener AppStatusListener took 9.283904906s.
[2024-10-24T01:33:56.034+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-10-24T01:34:01.237+0000] {spark_submit.py:524} INFO - Hello from Spark!
[2024-10-24T01:34:01.282+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:01 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-10-24T01:34:01.806+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:01 INFO SparkUI: Stopped Spark web UI at http://de5108c6da1d:4040
[2024-10-24T01:34:01.966+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:01 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-10-24T01:34:01.983+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:01 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-10-24T01:34:02.260+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:02 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-10-24T01:34:03.011+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:03 INFO MemoryStore: MemoryStore cleared
[2024-10-24T01:34:03.014+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:03 INFO BlockManager: BlockManager stopped
[2024-10-24T01:34:03.412+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:03 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-10-24T01:34:03.461+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:03 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-10-24T01:34:19.673+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:18 INFO SparkContext: Successfully stopped SparkContext
[2024-10-24T01:34:59.855+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-10-24T01:35:25.268+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:25 INFO ShutdownHookManager: Shutdown hook called
[2024-10-24T01:35:25.272+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:25 INFO ShutdownHookManager: Deleting directory /tmp/spark-45ea6439-d48e-4775-ab9b-6da7be010868
[2024-10-24T01:35:25.450+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:25 INFO ShutdownHookManager: Deleting directory /tmp/spark-45ea6439-d48e-4775-ab9b-6da7be010868/pyspark-8a715433-a3fc-47b4-878a-b5a82a885556
[2024-10-24T01:35:25.470+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:25 INFO ShutdownHookManager: Deleting directory /tmp/spark-40e82a70-c3fd-4f7f-9375-3516129f1a15
[2024-10-24T01:35:25.991+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=api_openbrewerydb_to_silver_gold, task_id=Silver, execution_date=20231129T080000, start_date=20241024T012657, end_date=20241024T013525
[2024-10-24T01:35:26.119+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-10-24T01:35:26.319+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
