[2024-10-24T01:27:01.881+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-12-08T08:00:00+00:00 [queued]>
[2024-10-24T01:27:01.930+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-12-08T08:00:00+00:00 [queued]>
[2024-10-24T01:27:01.930+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2024-10-24T01:27:01.974+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): Silver> on 2023-12-08 08:00:00+00:00
[2024-10-24T01:27:01.983+0000] {standard_task_runner.py:57} INFO - Started process 9156 to run task
[2024-10-24T01:27:02.000+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_openbrewerydb_to_silver_gold', 'Silver', 'scheduled__2023-12-08T08:00:00+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/api_openbrewerydb_to_silver.py', '--cfg-path', '/tmp/tmpwtl_g6y0']
[2024-10-24T01:27:02.022+0000] {standard_task_runner.py:85} INFO - Job 147: Subtask Silver
[2024-10-24T01:27:02.267+0000] {task_command.py:415} INFO - Running <TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-12-08T08:00:00+00:00 [running]> on host de5108c6da1d
[2024-10-24T01:27:02.741+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rodrigo Araujo' AIRFLOW_CTX_DAG_ID='api_openbrewerydb_to_silver_gold' AIRFLOW_CTX_TASK_ID='Silver' AIRFLOW_CTX_EXECUTION_DATE='2023-12-08T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-08T08:00:00+00:00'
[2024-10-24T01:27:02.832+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2024-10-24T01:27:02.833+0000] {spark_submit.py:363} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark --queue root.default jobs/silver/api_openbrewerydb.py
[2024-10-24T01:27:32.418+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:32 INFO SparkContext: Running Spark version 3.5.3
[2024-10-24T01:27:32.424+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:32 INFO SparkContext: OS info Linux, 5.15.0-124-generic, amd64
[2024-10-24T01:27:32.452+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:32 INFO SparkContext: Java version 11.0.25
[2024-10-24T01:27:33.340+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:33 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-10-24T01:27:34.714+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO ResourceUtils: ==============================================================
[2024-10-24T01:27:34.717+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-10-24T01:27:34.718+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO ResourceUtils: ==============================================================
[2024-10-24T01:27:34.720+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO SparkContext: Submitted application: IngestaoSilver
[2024-10-24T01:27:34.953+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:34 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-10-24T01:27:35.090+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:35 INFO ResourceProfile: Limiting resource is cpu
[2024-10-24T01:27:35.097+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:35 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-10-24T01:27:35.747+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:35 INFO SecurityManager: Changing view acls to: ***
[2024-10-24T01:27:35.753+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:35 INFO SecurityManager: Changing modify acls to: ***
[2024-10-24T01:27:35.755+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:35 INFO SecurityManager: Changing view acls groups to:
[2024-10-24T01:27:35.757+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:35 INFO SecurityManager: Changing modify acls groups to:
[2024-10-24T01:27:35.759+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:35 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-10-24T01:27:39.009+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:39 INFO Utils: Successfully started service 'sparkDriver' on port 40119.
[2024-10-24T01:27:39.272+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:39 INFO SparkEnv: Registering MapOutputTracker
[2024-10-24T01:27:39.713+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:39 INFO SparkEnv: Registering BlockManagerMaster
[2024-10-24T01:27:40.290+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:40 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-10-24T01:27:40.291+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:40 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-10-24T01:27:40.316+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:40 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-10-24T01:27:40.564+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:40 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-bba3dbd2-cb50-40ce-ad24-9ad06e49cd10
[2024-10-24T01:27:40.888+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:40 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-10-24T01:27:41.255+0000] {spark_submit.py:524} INFO - 24/10/24 01:27:41 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-10-24T01:28:02.947+0000] {spark_submit.py:524} INFO - 24/10/24 01:28:02 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-10-24T01:29:35.451+0000] {spark_submit.py:524} INFO - 24/10/24 01:29:34 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2024-10-24T01:29:36.613+0000] {spark_submit.py:524} INFO - 24/10/24 01:29:36 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2024-10-24T01:29:39.327+0000] {spark_submit.py:524} INFO - 24/10/24 01:29:38 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2024-10-24T01:29:41.545+0000] {spark_submit.py:524} INFO - 24/10/24 01:29:41 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2024-10-24T01:29:43.158+0000] {spark_submit.py:524} INFO - 24/10/24 01:29:42 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2024-10-24T01:29:45.547+0000] {spark_submit.py:524} INFO - 24/10/24 01:29:45 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
[2024-10-24T01:29:48.449+0000] {spark_submit.py:524} INFO - 24/10/24 01:29:48 WARN Utils: Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
[2024-10-24T01:29:50.364+0000] {spark_submit.py:524} INFO - 24/10/24 01:29:49 WARN Utils: Service 'SparkUI' could not bind on port 4047. Attempting port 4048.
[2024-10-24T01:29:51.843+0000] {spark_submit.py:524} INFO - 24/10/24 01:29:51 WARN Utils: Service 'SparkUI' could not bind on port 4048. Attempting port 4049.
[2024-10-24T01:29:53.883+0000] {spark_submit.py:524} INFO - 24/10/24 01:29:53 WARN Utils: Service 'SparkUI' could not bind on port 4049. Attempting port 4050.
[2024-10-24T01:29:54.855+0000] {spark_submit.py:524} INFO - 24/10/24 01:29:54 WARN Utils: Service 'SparkUI' could not bind on port 4050. Attempting port 4051.
[2024-10-24T01:30:53.467+0000] {spark_submit.py:524} INFO - 24/10/24 01:30:53 INFO Utils: Successfully started service 'SparkUI' on port 4051.
[2024-10-24T01:32:26.528+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-10-24T01:33:34.837+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-10-24T01:34:03.706+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:03 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2024-10-24T01:34:42.652+0000] {spark_submit.py:524} INFO - 24/10/24 01:34:39 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2024-10-24T01:35:20.025+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:20 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2024-10-24T01:35:20.146+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:20 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2024-10-24T01:35:02.455+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-10-24T01:35:22.466+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:22 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2024-10-24T01:35:24.535+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:24 WARN TransportClientFactory: DNS resolution succeed for spark-master/172.22.0.3:7077 took 4452 ms
[2024-10-24T01:35:25.051+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:25 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 45197.
[2024-10-24T01:35:25.051+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:25 INFO NettyBlockTransferService: Server created on de5108c6da1d:45197
[2024-10-24T01:35:25.104+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:25 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-10-24T01:35:25.360+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:25 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, de5108c6da1d, 45197, None)
[2024-10-24T01:35:25.408+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:25 INFO BlockManagerMasterEndpoint: Registering block manager de5108c6da1d:45197 with 434.4 MiB RAM, BlockManagerId(driver, de5108c6da1d, 45197, None)
[2024-10-24T01:35:25.471+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:25 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, de5108c6da1d, 45197, None)
[2024-10-24T01:35:25.474+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:25 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, de5108c6da1d, 45197, None)
[2024-10-24T01:35:25.862+0000] {spark_submit.py:524} INFO - 24/10/24 01:35:25 INFO TransportClientFactory: Successfully created connection to spark-master/172.22.0.3:7077 after 894 ms (0 ms spent in bootstraps)
[2024-10-24T01:35:26.087+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-10-24T01:35:26.101+0000] {process_utils.py:131} INFO - Sending 15 to group 9156. PIDs of all processes in the group: [9236, 9653, 9156]
[2024-10-24T01:35:26.104+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 9156
[2024-10-24T01:35:26.105+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-10-24T01:35:26.113+0000] {spark_submit.py:654} INFO - Sending kill signal to spark-submit
[2024-10-24T01:35:26.149+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 183, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 438, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 492, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-10-24T01:35:26.164+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=api_openbrewerydb_to_silver_gold, task_id=Silver, execution_date=20231208T080000, start_date=20241024T012701, end_date=20241024T013526
[2024-10-24T01:35:26.196+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 147 for task Silver (Task received SIGTERM signal; 9156)
[2024-10-24T01:35:26.262+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=9236, status='terminated', started='01:27:02') (9236) terminated with exit code None
[2024-10-24T01:35:26.263+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=9156, status='terminated', exitcode=1, started='01:27:01') (9156) terminated with exit code 1
[2024-10-24T01:35:26.264+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=9653, status='terminated', started='01:27:24') (9653) terminated with exit code None
[2024-10-24T14:36:52.947+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-12-08T08:00:00+00:00/task_id=Silver permission to 509
[2024-10-24T14:36:52.955+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-12-08T08:00:00+00:00/task_id=Silver permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-12-08T08:00:00+00:00/task_id=Silver'
[2024-10-24T14:36:52.983+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-12-08T08:00:00+00:00/task_id=Silver permission to 509
[2024-10-24T14:36:52.983+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-12-08T08:00:00+00:00/task_id=Silver permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-12-08T08:00:00+00:00/task_id=Silver'
[2024-10-24T14:36:53.012+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-12-08T08:00:00+00:00 [queued]>
[2024-10-24T14:36:53.019+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-12-08T08:00:00+00:00 [queued]>
[2024-10-24T14:36:53.019+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-10-24T14:36:53.029+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): Silver> on 2023-12-08 08:00:00+00:00
[2024-10-24T14:36:53.034+0000] {standard_task_runner.py:57} INFO - Started process 15514 to run task
[2024-10-24T14:36:53.036+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_openbrewerydb_to_silver_gold', 'Silver', 'scheduled__2023-12-08T08:00:00+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/api_openbrewerydb_to_silver.py', '--cfg-path', '/tmp/tmpzhswv8ng']
[2024-10-24T14:36:53.037+0000] {standard_task_runner.py:85} INFO - Job 101: Subtask Silver
[2024-10-24T14:36:53.083+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-12-08T08:00:00+00:00/task_id=Silver permission to 509
[2024-10-24T14:36:53.084+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-12-08T08:00:00+00:00/task_id=Silver permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-12-08T08:00:00+00:00/task_id=Silver'
[2024-10-24T14:36:53.084+0000] {task_command.py:415} INFO - Running <TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-12-08T08:00:00+00:00 [running]> on host 96f89615839b
[2024-10-24T14:36:53.163+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rodrigo Araujo' AIRFLOW_CTX_DAG_ID='api_openbrewerydb_to_silver_gold' AIRFLOW_CTX_TASK_ID='Silver' AIRFLOW_CTX_EXECUTION_DATE='2023-12-08T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-08T08:00:00+00:00'
[2024-10-24T14:36:53.174+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2024-10-24T14:36:53.175+0000] {spark_submit.py:363} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark jobs/silver/api_openbrewerydb.py
[2024-10-24T14:36:55.878+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:55 INFO SparkContext: Running Spark version 3.5.3
[2024-10-24T14:36:55.880+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:55 INFO SparkContext: OS info Linux, 5.15.0-124-generic, amd64
[2024-10-24T14:36:55.880+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:55 INFO SparkContext: Java version 11.0.25
[2024-10-24T14:36:55.938+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:55 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-10-24T14:36:56.031+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO ResourceUtils: ==============================================================
[2024-10-24T14:36:56.031+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-10-24T14:36:56.031+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO ResourceUtils: ==============================================================
[2024-10-24T14:36:56.032+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO SparkContext: Submitted application: IngestaoSilver
[2024-10-24T14:36:56.056+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-10-24T14:36:56.072+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO ResourceProfile: Limiting resource is cpu
[2024-10-24T14:36:56.073+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-10-24T14:36:56.128+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO SecurityManager: Changing view acls to: ***
[2024-10-24T14:36:56.128+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO SecurityManager: Changing modify acls to: ***
[2024-10-24T14:36:56.129+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO SecurityManager: Changing view acls groups to:
[2024-10-24T14:36:56.130+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO SecurityManager: Changing modify acls groups to:
[2024-10-24T14:36:56.130+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-10-24T14:36:56.415+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO Utils: Successfully started service 'sparkDriver' on port 45625.
[2024-10-24T14:36:56.448+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO SparkEnv: Registering MapOutputTracker
[2024-10-24T14:36:56.488+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO SparkEnv: Registering BlockManagerMaster
[2024-10-24T14:36:56.514+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-10-24T14:36:56.515+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-10-24T14:36:56.519+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-10-24T14:36:56.541+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-d2157f54-6d02-4dd0-821d-0403f3864a6a
[2024-10-24T14:36:56.559+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-10-24T14:36:56.575+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-10-24T14:36:56.712+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-10-24T14:36:56.760+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-10-24T14:36:56.891+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2024-10-24T14:36:56.942+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:56 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.2:7077 after 29 ms (0 ms spent in bootstraps)
[2024-10-24T14:36:57.038+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:57 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20241024143657-0096
[2024-10-24T14:36:57.054+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:57 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241024143657-0096/0 on worker-20241024142308-172.18.0.5-43899 (172.18.0.5:43899) with 2 core(s)
[2024-10-24T14:36:57.071+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:57 INFO StandaloneSchedulerBackend: Granted executor ID app-20241024143657-0096/0 on hostPort 172.18.0.5:43899 with 2 core(s), 1024.0 MiB RAM
[2024-10-24T14:36:57.096+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:57 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 36927.
[2024-10-24T14:36:57.096+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:57 INFO NettyBlockTransferService: Server created on 96f89615839b:36927
[2024-10-24T14:36:57.099+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:57 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-10-24T14:36:57.108+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:57 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241024143657-0096/0 is now RUNNING
[2024-10-24T14:36:57.117+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:57 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 96f89615839b, 36927, None)
[2024-10-24T14:36:57.119+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:57 INFO BlockManagerMasterEndpoint: Registering block manager 96f89615839b:36927 with 434.4 MiB RAM, BlockManagerId(driver, 96f89615839b, 36927, None)
[2024-10-24T14:36:57.123+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:57 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 96f89615839b, 36927, None)
[2024-10-24T14:36:57.125+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:57 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 96f89615839b, 36927, None)
[2024-10-24T14:36:57.408+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:57 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-10-24T14:36:57.638+0000] {spark_submit.py:524} INFO - Hello from Spark!
[2024-10-24T14:36:57.639+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:57 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-10-24T14:36:57.651+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:57 INFO SparkUI: Stopped Spark web UI at http://96f89615839b:4040
[2024-10-24T14:36:57.657+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:57 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-10-24T14:36:57.662+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:57 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-10-24T14:36:57.679+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:57 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-10-24T14:36:57.688+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:57 INFO MemoryStore: MemoryStore cleared
[2024-10-24T14:36:57.688+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:57 INFO BlockManager: BlockManager stopped
[2024-10-24T14:36:57.693+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:57 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-10-24T14:36:57.695+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:57 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-10-24T14:36:57.702+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:57 INFO SparkContext: Successfully stopped SparkContext
[2024-10-24T14:36:58.015+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:58 INFO ShutdownHookManager: Shutdown hook called
[2024-10-24T14:36:58.015+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:58 INFO ShutdownHookManager: Deleting directory /tmp/spark-11658d72-8db5-4a2d-ba0d-1dbdd90354af
[2024-10-24T14:36:58.019+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:58 INFO ShutdownHookManager: Deleting directory /tmp/spark-11658d72-8db5-4a2d-ba0d-1dbdd90354af/pyspark-18671aaf-fceb-44f0-aabf-45236c1ed013
[2024-10-24T14:36:58.021+0000] {spark_submit.py:524} INFO - 24/10/24 14:36:58 INFO ShutdownHookManager: Deleting directory /tmp/spark-bd76885f-4773-44e1-84c7-bd4e1b06f188
[2024-10-24T14:36:58.084+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=api_openbrewerydb_to_silver_gold, task_id=Silver, execution_date=20231208T080000, start_date=20241024T143653, end_date=20241024T143658
[2024-10-24T14:36:58.106+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-10-24T14:36:58.127+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
